//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace exem
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Cours
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cours()
        {
            this.Grades = new HashSet<Grade>();
        }

        public override int GetHashCode()
        {
            return this.ID;
        }

        public int ID { get; set; }
        public string NAME { get; set; }
        public int HOURS { get; set; }
        public Nullable<int> AVG_GRADE { get; set; }
        public Nullable<int> NUM_OF_STUDENTS { get; set; }
        public Nullable<int> HIGHEST_GRADE { get; set; }
        [JsonIgnore]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Grade> Grades { get; set; }
    }
}
